language: objective-c

before_install: 
- gem install cocoapods
- brew update
- brew install xctool
- brew upgrade

script: 
- xctool -workspace JSQMessages.xcworkspace -scheme JSQMessagesDemo -sdk iphonesimulator7.0 ONLY_ACTIVE_ARCH=NO clean build
- xctool -workspace JSQMessages.xcworkspace -scheme JSQMessagesTests -sdk iphonesimulator7.0 ONLY_ACTIVE_ARCH=NO clean build run-tests -freshInstall
