language: objective-c

before_install: 
- export LANG=en_US.UTF-8
- gem install cocoapods
- brew update
- brew unlink xctool
- brew install xctool

script: 
- xctool clean build test -workspace JSQMessages.xcworkspace -scheme JSQMessages -sdk iphonesimulator7.1
